inherit_from:
  - '.rubocop-rspec.yml'

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  # Exclude:
 
Naming/FileName:
  Exclude:
  # - "**/Gemfile"
  - "**/Rakefile"
  - "**/Fastfile"
  - "**/*.gemspec"

Style/MultipleComparison:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/MutableConstant:
  Enabled: false

# Performance/RegexpMatch:
#   Enabled: false

# Performance/StringReplacement:
#   Enabled: false

Style/NumericPredicate:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

# Style/MethodMissingSuper:
#   Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiteralPrefix:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

# Style/EmptyMethod:
#   Enabled: true

# Style/BracesAroundHashParameters:
#   Enabled: false

Lint/UselessAssignment:
  Exclude:
  - "**/spec/**/*"

Style/SymbolArray:
  Enabled: false

Style/MixinGrouping:
  Exclude:
  - "**/spec/**/*"

Lint/UnusedBlockArgument:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/WordArray:
  MinSize: 19

Style/SignalException:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: conditionals

Metrics/ClassLength:
  Max: 320

Layout/LineLength:
  Max: 370

Metrics/ParameterLists:
  Max: 17

Style/GuardClause:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Exclude:
  - "**/spec/**/*"

Naming/PredicateName:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

# check which of these methods we are using
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
  - require
  - require_relative
  - load
  - fastlane_require
  - gem
  - program
  - command
  - raise
  - attr_accessor
  - attr_reader
  - desc
  - lane
  - private_lane
  - platform
  - to
  - describe
  - it
  - be
  - context
  - before
  - after

Gemspec/RequireMFA:
  Enabled: false
