name: CI Workflow

on:
  # pull_request:
  push:
    branches:
      - master
      - feature/adding-CI/CD-pipeline

jobs:
  lint-and-test:
    name: lint-and-test-Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.7, 3.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Lint
        run: bundle exec rake rubocop
      - name: Test
        run: bundle exec rake spec

  build:
    name: build-Ruby ${{ matrix.ruby}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.7, 3.0]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true 
      - name: Build
        run: |
          bundle exec rake build
          cd pkg && ls -la
    needs: lint-and-test