name: CI Workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Lint
        run: bundle exec rake rubocop
      - name: Test
        run: bundle exec rake spec

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true 
      - name: Build
        run: |
          bundle exec rake build
          cd pkg && ls -la
    needs: lint-and-test